### ISSUE TITLE
Python usage example is incorrect

### ISSUE THREAD

**Issue by merkys** [himynameisfuego/decomposeSTN#1]
The following Python usage example is incorrect:
https://github.com/himynameisfuego/decomposeSTN/blob/8eb5d4ab6b3a62ed0efeee6b8a2e6f34109c381b/README.md?plain=1#L36
Instead, it should be:
```Python
[xs, xt, xn] = STN.decSTN(audioInput,Fs,nWin1,nWin2)
```

**Comment by himynameisfuego** [comment]
@merkys thanks for catching that! I will fix it right away.
